### ISSUE TITLE
Compilation on aarch64 and CI issue

### ISSUE THREAD

**Issue by psstoyanov** [francescmm/GitQlient#102]
Hi, I'm having trouble compiling on aarch64. The CI build system seems to be using predefined x86 executable for `qmake` and `linuxdeployqt` 

Device: Pinebook Pro running Manjaro ARM (aarch64 userland)
SOC: RK3399 

Error:
```
 ./ci-scripts/linux/build.sh 
g++ (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

./ci-scripts/linux/build.sh: line 9: /home/pak0st/ProgramsToCompile/GitQlient/qt5/bin/qmake: cannot execute binary file: Exec format error
./ci-scripts/linux/build.sh: line 10: /home/pak0st/ProgramsToCompile/GitQlient/qt5/bin/qmake: cannot execute binary file: Exec format error
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat 'GitQlient': No such file or directory
./ci-scripts/linux/build.sh: line 17: ./linuxdeployqt: cannot execute binary file: Exec format error
chmod: cannot access 'GitQlient-*': No such file or directory
cp: cannot stat 'GitQlient-*': No such file or directory
```

**Comment by francescmm** [comment]
Hi @psstoyanov,

The CI scripts are not planned to be used as a general building environment. They download and make the compilation with a specific Qt version for x86 architecture.

To compile for aarch64 you would need the Qt libraries, qmake, etc. for that platform.

**Comment by psstoyanov** [comment]
Thanks, @francescmm . I should've dug more into the wiki before making the ticket. The setup is prepared on machine and the [ build instructions](https://francescmm.github.io/GitQlient/#appendix-b-build) opened.

Will give it a go tonight
