### ISSUE TITLE
Bug: pushing local branch does not create a remote branch

### ISSUE THREAD

**Issue by fklappan** [francescmm/GitQlient#104]
Version 1.1.0
OS Linux Manjaro (KDE)

A newly created local branch is not created on the server after push.

**Reproduce**
- create new branch (either in "local" or "remote" view)
- push immediately 
OR
- commit some changes
- push
- the branch is not pushed to origin

**Expected behavior**
The branch should be created on origin and tracked by the local branch

**Comment by francescmm** [comment]
Hi @fklappan,

I was wondering where are you starting a branch from. I've tried several ways and the only time it didn't work was when I was detached from any other branch. In GitQlient it should appear as "detached".

Is the same happening to you?

**Comment by fklappan** [comment]
I try to start the branch from within the "local" branches area, right clicking on "master" (please see attached screenshot):
![image](https://user-images.githubusercontent.com/5860600/86527583-87c37580-bea0-11ea-8d6f-f49bc7dbee0c.png)

From the "local" view: 
- right click on master
- choose "Create & checkout branch"
- name it "test" and accept with "Create"

We now have a branch named "test" with origin "Local":
![image](https://user-images.githubusercontent.com/5860600/86527635-51d2c100-bea1-11ea-934e-f0d7d25f08f4.png)

- commit some changes
- press the "Push" button

Result: the branch still is only local:
![image](https://user-images.githubusercontent.com/5860600/86527658-86df1380-bea1-11ea-80be-be8fe752d440.png)
Screenshot was taken **after** pushing. See the little "upstream" icon, showing "1" with arrow up. It was not pushed.

**Additional information**
- I cloned the repository through SSH
- "git push --set-upstream origin test" through console from directory works as usual

**Comment by francescmm** [comment]
Cool! Thanks for the full report, this is going to be really useful. Just to be 100% sure, could you confirm me that the commit associated to the version is **caed16703d3ff515748cde80da31ddfef8e436d1**?

You can find it as tool tip (wait 1 sec.) when passing over "About GitQlient v1.1.0 ..." link in the main screen:

![image](https://user-images.githubusercontent.com/4884514/86534886-74ce9680-bedc-11ea-9aa7-02a92aa3bfae.png)

**Comment by fklappan** [comment]
Got GitQlient from the [AUR](https://aur.archlinux.org/packages/gitqlient/) through `git clone https://aur.archlinux.org/gitqlient.git`

Screenshot of commit sha:
![image](https://user-images.githubusercontent.com/5860600/86536081-1bb73080-bee5-11ea-9791-62e6f5c5b54a.png)

**Comment by francescmm** [comment]
BTW @fklappan did you manage to reproduce this on develop?

**Comment by fklappan** [comment]
Develop works as expected. It's only on version 1.1.0

Francesc M. <notifications@github.com> schrieb am Do., 9. Juli 2020, 19:58:

**Comment by francescmm** [comment]
Thanks! Since this is not happening in develop and so in the future 1.2.0, I've decided to not move forward with the fix.

The new version is going to be ready really soon and I cannot even reproduce it locally on 1.1.0.
