### ISSUE TITLE
Fix Qt 5.15 deprecations

### ISSUE THREAD

**Issue by fklappan** [francescmm/GitQlient#106]
With Qt 5.15 some of the used classes or methods are deprecated.
As I'm working on a fresh Manjaro installation, Qt 5.15 is installed by default.

With this setup I'm not able to build GitQlient because of deprecation errors. Unfortunately the `QT_DISABLE_DEPRECATED_BEFORE` flag in the .pro file does not help.

So for compiling the project with my setup it is needed to fix the deprecated errors (or at least jump through some hoops installing Qt 5.13 - but we need to fix these warnings anyway).

Although I'm a bit rusty with Qt, I would try to do it by myself. I just need your "Go" that you are not already working on this. 
If you are already working on it, you now have a ticket to close ;-)

**Comment by francescmm** [comment]
Hi @fklappan,

I'm not working on that so feel free to send a PR with the changes! I will try the changes with Qt 5.9 since I'd like to support it at least until we change to Qt6.

Thanks for the proactivity!

**Comment by francescmm** [comment]
@fklappan sorry for the sudden change, but I'm gonna fix it today. I think this will help you. Give me some minutes ;)

**Comment by francescmm** [comment]
@fklappan done! It's on develop, so if you can pull you should be able to compile GitQlient now! :)
