### ISSUE TITLE
Staged files can be "lost" on commit

### ISSUE THREAD

**Issue by laurent-simon** [francescmm/GitQlient#107]
If there are entries in the staged files list, the commit summary is left blank, and if you try to commit then: 

- An error message is displayed: normal
- The staged files list is cleared: __Its content is lost__ :-(

As long as the commit is not done and the files are not removed, the staged files list state must not change.

**Comment by francescmm** [comment]
Hi @laurent-simon,

I'm sorry but I couldn't reproduce the issue as you describe. I tried two different things with v1.1.0 and in the develop branch:

1. Try to commit without summary nor description: The staged file remains there
2. Try to commit without summary but with description: The commit is done, the description is added as summary.

Could you add a more step-by-step guide of how you did it?

**Comment by laurent-simon** [comment]
Ok sorry, you are right. Due to the previous issue, I suspected the 1.1.0-rc to be unstable and I tried the 1.0.0. This problem exists only on the 1.0.0. I cannot reproduce it on the 1.1.0-rc.

**Comment by francescmm** [comment]
Hi @laurent-simon, remember that there is a [final 1.1.1](https://github.com/francescmm/GitQlient/releases/tag/v1.1.1) too!
