### ISSUE TITLE
Unadapted colors: need a way to change this

### ISSUE THREAD

**Issue by laurent-simon** [francescmm/GitQlient#109]
The colors theme does not respect the system settings. This is annoying (and very hard to read) within a clear system theme environment.

For a more usable application, a way to change the colors theme, or to respect the system ones, will be greatly appreciated.

For example, QGit colors are far, far better, for my taste...

**Comment by francescmm** [comment]
Hi @laurent-simon, in the next version there is a new bright colors schema. This is solved in #24. Are you open to compile the _**develop**_ branch? You can have it in there already.
