### ISSUE TITLE
Feature Request: actions from Diff-View

### ISSUE THREAD

**Issue by fklappan** [francescmm/GitQlient#114]
I noticed I'm forced to switch between the diff view to check changes and the history view to stage or revert them. I think this workflow is cumbersome and error prone and would be better if I could revert or state changes directly from the diff view.

I have already checked the changes on a specific file but need to switch the view and select it another time to stage or revert it. If I have lots of changes it is hard to find the correct file and I could accidentially revert the wrong file.

What do you think?

**Comment by francescmm** [comment]
I totally agree!

When I started the Diff Widget I thought as a quick way to check what changed. Now, GitQlient brings more functionality like the edition of files in place, so I think it makes sense to iterate again and re-design the diff view.

I also need to figure out how to integrate myself the issue #19 and #26. So, definitely this must go in at the same time.

**Comment by francescmm** [comment]
I've included the changes in 1.2.0. I'll need to add a whole new user manual section for this.
