### ISSUE TITLE
Feature Request: Add option to use native style

### ISSUE THREAD

**Issue by Schlumpf** [francescmm/GitQlient#137]
Please add an option to disable the CSS theme and use the native style, provided by the OS.
The app feels like a foreign object on my system (default KDE Plasma5 theme). It doesn't match the look and feel of the rest of the desktop.

**Comment by francescmm** [comment]
Hi @Schlumpf,

I can add an option to use native style for the next version 1.2.0, sure!

**Comment by francescmm** [comment]
Hi @Schlumpf,

I've been doing some visual tests and it's more complicated that it could seem. Have you tried the "bright" version currently on develop branch?

**Comment by francescmm** [comment]
After deeper analysis, having _default_ styles is not an options since they are quite embedded with the behaviour (branches, labels, graph colors...).
