### ISSUE TITLE
Haiku OS Support

### ISSUE THREAD

**Issue by cyrusbuilt** [francescmm/GitQlient#138]
I was just wondering if you could include a minor change to Controls.cpp that enables GitClient to build and run on Haiku OS using the Haiku port of QT 5.15.0.  I was able to clone the repo and make the following change that took care of it:

In void Controls::processUpdateFile():

#if defined(Q_OS_WIN)
   const auto os = json["windows"].toObject();
#elif defined(Q_OS_LINUX)
   const auto os = json["linux"].toObject();
#elif defined(Q_OS_OSX)
   const auto os = json["osx"].toObject();
#elif defined(Q_OS_HAIKU)                                    <--- This define exist in the Haiku port of Qt.
   const auto os = json["haiku"].toObject();
#endif

And that's it.  Of course, I imagine that the updates.json file would need to modified for the update check to work correctly, but this takes care of the actually platform compatibility.  No other platform-specific changes were required as far as I can tell.  I've been using GitQlient from Haiku after that change all day so far without issue.

**Comment by francescmm** [comment]
HI @cyrusbuilt no problem at all with the change. For now I've added an else statement instead of a Q_OS_HAIKU since I don't support the updates on that OS (for now, once #139 is done I'll modify the code).

Let me know if this works and I'll close the issue.

**Comment by cyrusbuilt** [comment]
That worked!

**Comment by francescmm** [comment]
I'll update the code tomorrow to actually disable the download but keep notifying the user that a new version is available for those OS I don't support yet.
