### ISSUE TITLE
[BUG] Top bar icons don't appear

### ISSUE THREAD

**Issue by Pontation** [francescmm/GitQlient#140]
**Describe the bug**
When running GitQlient on Windows, the top bar doesn't appear.

**To Reproduce**
1. From the landing page, choose open and select a valid repository

**Expected behavior**
The top bar should have clear icons

**Screenshots**
![image](https://user-images.githubusercontent.com/3776412/90369965-de5dcb00-e06c-11ea-8822-38a2ce922841.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release version or SHA: Official release 1.2.0

**Comment by francescmm** [comment]
Hi @Pontation,

I saw there was a problem with the installation: some files where not copied. I've released a new installer and make sure that the .dll that windows need are copied.

Thanks for reporting this!

**Comment by Pontation** [comment]
@francescmm I can confirm the new installer doesn't have this problem, thanks.
