### ISSUE TITLE
What tool is used to package and integrate the GitQlientInstaller-1.2.0.exe installation package?

### ISSUE THREAD

**Issue by libaineu2004** [francescmm/GitQlient#145]
**What current behavior doesn't fully fit your needs? Why?**
What tool is used to package and integrate the GitQlientInstaller-1.2.0.exe installation package?

**What you'd like to see? Propose a solution**
Is it a self-developed package program? Where is the source code?

**Describe alternatives you've considered**

**Additional context**

**Comment by francescmm** [comment]
The tool is a proprietary software, so the source code is private.
