### ISSUE TITLE
What is the software name of the installer? Where can I download it?

### ISSUE THREAD

**Issue by libaineu2004** [francescmm/GitQlient#146]
**What current behavior doesn't fully fit your needs? Why?**
I previously submitted a question:
https://github.com/francescmm/GitQlient/issues/145
Your answer is that the packager has no source code? Then I want to ask another question:
What is the software name of the installer? Where can I download it?
Thank you.

**What you'd like to see? Propose a solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by francescmm** [comment]
I've used several package installers. You can find them with a quick search on Google: https://www.google.com/search?q=installer+packager+windows

You have [Advanced Installer](https://www.advancedinstaller.com/), [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/index.html).

Please, in the future keep the issues for real GitQlient development related questions.
