### ISSUE TITLE
Feature request: Add complete folder to .gitignore

### ISSUE THREAD

**Issue by hilpara** [francescmm/GitQlient#147]
It would be nice to have possibility to add complete folder to .gitignore. When right clicking the file, it is possible to select Ignore file or Ignore extension, would it be possible to have also ignore folder and ignore pattern?

**Comment by francescmm** [comment]
HI @hilpara,

I can add the "ignore containing folder" option, but to add an ignore for more complex patter can be achieved by editing the file in any editor.

Maybe in a future version I can add an option to manually edit .gitignore and .gitmodules files but not a priority right now.
