### ISSUE TITLE
If the cloned repository is empty, it is not possible to commit.

### ISSUE THREAD

**Issue by hilpara** [francescmm/GitQlient#148]
If new repository is created with git init --bare, there aren't any branches before first commit. If the repository is cloned with GitQClient, it is not possible to make this first commit. The GitQClient doesn't see any files added to cloned repository folder before at least one file is added to git, with git add and commited with git commit.

**Comment by francescmm** [comment]
Hi @hilpara could you tell me what version are you using? I think I remember a similar issue but I thought it was solved.

**Comment by hilpara** [comment]
I'm using 1.2.0

**Comment by francescmm** [comment]
Hi @hilpara 

If pushed the changes in the **_develop_** branch in case you want to test them further. It will be included in the 1.3.0 version.

Thanks for reporting it! :smiley:
