### ISSUE TITLE
License issue with font Ubuntu

### ISSUE THREAD

**Issue by hegjon** [francescmm/GitQlient#156]
I could not find info about the license for `Ubuntu.ttf` and `UbuntuMono.ttf` in this repo, so I assume it is Ubuntu Font Licence.

These fonts are bundled with the executable.

According to both Debian and Fedora, they will not allow redistributing these fonts.

https://bugs.launchpad.net/ubuntu-font-licence/+bug/769874
https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4

**Comment by francescmm** [comment]
That sucks... Since it's a blocker (stupid but blocker) I'll put that in top of my _todo_ list... :facepalm:

**Comment by francescmm** [comment]
Done! :D

**Comment by francescmm** [comment]
This unblocks #73
