### ISSUE TITLE
[BUG] Maximize window does not work

### ISSUE THREAD

**Issue by Symbian9** [francescmm/GitQlient#190]
**Describe the bug**

Maximize window (via default system shortcut, e.g. <kbd>F11</kbd>) does NOT work.

**To Reproduce**
1. Launch app;
2. Try to maximize window.

**Expected behavior**
Maximize window should work as expected (e.g. should switch to *fullscreen* mode).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Debian 10 buster)
 - Release version or SHA: `1.3.0` ( `GitQlient-1.3.0-x86_64.AppImage`)
 - If manually compiled, compiler version: 

**Additional context**

- https://www.computerhope.com/jargon/m/maximize.htm

**Comment by francescmm** [comment]
Hi, could you add a screenshot to see if the buttons are shown in the window
frame?

Take into account that shortcuts are not processed yet by GitQlient. So it
might not work via F11.

**Comment by Symbian9** [comment]
> Hi, could you add a screenshot to see if the buttons are shown in the window
frame?

Yes, window frame buttons are shown.

To be clear, ***until any project is open*** maximize button on window frame could maximize GitQlient window.

BUT ***just after opening any project*** window maximizing STOPPED to work!

Closing all projects tabs returns maximizing back, so ***it seems like project tab layout prevents maximizing***.

![pic.1](https://i.imgur.com/x3cw3Jq.png)

> Take into account that shortcuts are not processed yet by GitQlient. So it
might not work via F11.

OK, got it. But hope it would be fixed too.

**Comment by francescmm** [comment]
For what I'm seeing, the screen resolution could be an issue. I've optimized GitQlient for a 1920x1080 screen and didn't check that much for lower resolutions. Fixed sizes could be why this is not allowing to maximize, for strange that it can look :thinking: I could open a ticket or modify this one to make it work with lower resolutions.

About the shortcuts, there is already an issue in the backlog to add them to GitQlient :smiley:

**Comment by Symbian9** [comment]
> to make it work with lower resolutions

Yes, please! Actually initial (default) GitQlient screen size *on "clean install"* (without decorations) uses `822x480 px`.

![pic.2](https://i.imgur.com/6NqSopz.png)

So, I highly recommends optimize GitQlient to be usable starting from `720x480 px` (and set it as minimal window size).

**Comment by francescmm** [comment]
To be fair I don't think I can manage that size. I could try 1024x768, but only try. I think that right now 1080 it's quite standard.

However, I see that for really small screens it could be usefull to have it. In this case, though, I would go for creating a _minimalistic_ version of GitQlient. I cannot fit anything that is part of the main view of GitQlient on that size.

I'm interested in knowing what are the features you use the most of GitQlient.

**Comment by francescmm** [comment]
I'll create further work for reviewing the resolution in the future. Thanks for let me know about it.

**Comment by Symbian9** [comment]
> I'll create further work for reviewing the resolution in the future

Please, make minimal window size for fullscreen at least `1280x720` for GitQlient `v1.3.1`!
