### ISSUE TITLE
Reduce the size of the binaries

### ISSUE THREAD

**Issue by francescmm** [francescmm/GitQlient#191]
GitQlient right now is using several Qt binaries for just some minor features.

The way GitQlient manages SVG could be simplified so it doesn't require QtSvg.

Regarding the QtWebEngineWidgets and QtWebChannel libraries, both can be moved out of GitQlient when the GitHub/GitLab integration becomes an optional library.

**Comment by eraxillan** [comment]
Just for history i will note that QtWebEngineWidgets and QtWebChannel are absent in Qt6.  
About QtSvg: as a user i don't suffer from this module, if it really simplify program code.  
Even all Qt libraries at all cannot be compared with simplest Electron app :)

**Comment by francescmm** [comment]
QtSvg has been removed as dependency but for functionality I'll keep QtWebEngineWidgets and QtWebChannel.
