### ISSUE TITLE
Portable version for Windows?

### ISSUE THREAD

**Issue by ava1ar** [francescmm/GitQlient#193]
**What current behavior doesn't fully fit your needs? Why?**
Right now the only way to get GitQlient on Windows is to use installer. Problem is that it requires admin permissions to install the app. I don't have admin permissions on my corporate PC and I don't think they really needed to install the application like this.

**What you'd like to see? Propose a solution**
Either update the installer so it can be used with no admin account or simply provide portable version (just an archive with all required files), so it can be used without installation.

**Comment by francescmm** [comment]
Hi,

Thanks for reporting! I'll make sure it's modified for 1.3.1 :smiley:
