### ISSUE TITLE
[BUG] Program's window doesn't fit a 2560x1440 display

### ISSUE THREAD

**Issue by prokoudine** [francescmm/GitQlient#194]
1. Open any repository on a HiDPI display with 2560x1440 resolution on Linux (Ubuntu 20.10)
2. The program's window simply doesn't fit the display.

![Screenshot from 2021-02-12 23-47-40](https://user-images.githubusercontent.com/57467/107821401-6bb87880-6d8d-11eb-92b0-f234c3ec7e54.png)

**Comment by francescmm** [comment]
Hi,

Thanks for reporting this. GitQlient is supposed (via Qt code) to be set up for HiDPI so definitely a bug I'll try to solve in 1.3.1.

**Comment by eraxillan** [comment]
Well, sorry for stupid question, but the problem is that "maximize" button is absent, isn't it?   
On my desktop environment (latest Fedora + Gnome) it present, and window looks like ok in 4K resolution.  
However, it's a pain what commit/branch information panes cannot be resized.  

![Screenshot from 2021-02-17 16-37-47](https://user-images.githubusercontent.com/5300377/108212333-cad80d80-713e-11eb-9776-afd1cc81c279.png)

**Comment by francescmm** [comment]
Hi @eraxillan and thanks for the feedback! The branches panel can be "minimized" but it's true that either of those are resizable right now. I would ask you to open a different ticket for that.

**Comment by prokoudine** [comment]
@eraxillan "Well, sorry for stupid question, but the problem is that "maximize" button is absent, isn't it?" — no, it's not, and the reason you are not seeing this is because your resolution is 3840×2400 rather than 2560×1440, and that's quite a difference :)

**Comment by eraxillan** [comment]
@prokoudine lol, now i got it :)
Adaptable UI is a pain even in 2021 although.

**Comment by francescmm** [comment]
Hi @prokoudine I was revisiting this issue and I was wondering if you have a different % for the font-size in your desktop.

I also have another doubt: are you using several monitors with different dpi?

In any case, it would be really nice if you could try to compile the branch **testing-hdpi** that I just created with an additional flag. If for any reason you're compiling an older version of GitQlient (but with Qt >= 5.14), could you add the following line before QApplication declaration in main.cpp? 
`qputenv("QT_ENABLE_HIGHDPI_SCALING", "1");`

**Comment by francescmm** [comment]
@prokoudine I've done some changes in the **develop** branch that I think it might help you. The minimum size right now should fit your monitor even with HiDPI (up to 200%). Could you give it a try?

**Comment by Symbian9** [comment]
> The minimum size right now should fit your monitor even with HiDPI (up to 200%). Could you give it a try?

I just tried *GitQlient* `1.3.1` — it is NOT fit my display now (i.e. `1280x800`), even worst as it was in `1.3.0`

Now it seems like minimum window size even larger than it was `1.3.0` (See previous unsolved issue report: https://github.com/francescmm/GitQlient/issues/190)

- If Top-Left corner pinned — Bottom-Right corner out of window size:
  ![pic.1](https://i.imgur.com/UaKYEDZ.png)
- If Bottom-Right corner pinned —  Top-Left corner pinned of window size:
  ![pic.2](https://i.imgur.com/osi6t8L.png)

**Comment by francescmm** [comment]
@Symbian9 does the window allow you to resize the window? I don't know for the icons if that's possible by the top bar icons.

**Comment by Symbian9** [comment]
> does the window allow you to resize the window?

Yes, but only *enlarging*.

Also window maximizing does NOT work.

**Comment by francescmm** [comment]
@Symbian9 are you using 200% DPI, right? Just to try to reproduce it.

**Comment by Symbian9** [comment]
> are you using 200% DPI, right?

Probably not. I just use default settings.

What you mean under "200% DPI" settings?


Here are my appearance settings:

![pic.1](https://i.imgur.com/fPd7WhU.png) ![pic.2](https://i.imgur.com/YDx1hiQ.png)

**Comment by prokoudine** [comment]
> @prokoudine I've done some changes in the **develop** branch that I think it might help you. The minimum size right now should fit your monitor even with HiDPI (up to 200%). Could you give it a try?

I just did. Unfortunately, it's the same.

**Comment by francescmm** [comment]
@Symbian9 @prokoudine I just find a way to reproduce it locally, so I'll spend some time this weekend. Let's see if I can release a 1.3.2 with the problem solved!

I'll push all the changes to develop first just in case you could test it. If it works I'll push them to master and do the release :smile:

**Comment by francescmm** [comment]
@Symbian9 @prokoudine let's hope this commit solves the issue! :crossed_fingers: 

Just pushed to develop :smiley:

**Comment by Symbian9** [comment]
> I'll push all the changes to develop first just in case you could test it.

As you there are no `continuous` builds (see https://github.com/francescmm/GitQlient/issues/70) how would I test it?

Please, provide AppImage binary build for testing.

**Comment by francescmm** [comment]
@Symbian9 compiling the code would work. For this time I generated a pre-release for it: https://github.com/francescmm/GitQlient/releases/tag/v1.3.2-rc

**Comment by Symbian9** [comment]
> compiling the code would work.

I'm testing official builds and never compile it from source itself.

>  For this time I generated a pre-release for it.

Got it.

Seems like now it's works!

Just few notes:

- After launch `GitQlient-1.3.2-x86_64.AppImage` it starts in `bright` theme (by ignoring `dark` theme from previous config file);
- Switching to another theme should immoderately triggered on <kbd>Apply</kbd> — otherwise there should be shown a message "Restart to apply changes";

![pic.1](https://i.imgur.com/aQCw0em.png)

**Comment by francescmm** [comment]
@Symbian9 happy to hear that it works!

I've checked the style thing and it was a regression introduced in 4020e7005c68d9b4f17191b1aa736bee6d036595. I've fixed it in both master and develop, so I'll trigger a new release really really soon!
