### ISSUE TITLE
Make information panels resizeable

### ISSUE THREAD

**Issue by eraxillan** [francescmm/GitQlient#197]
Extracted from #194:
> The branches panel can be "minimized" but it's true that either of those are resizable right now. I would ask you to open a different ticket for that.

Left panel with commit info (author, diff, etc.) and right panel with branches, tags, submodules should be resizeable.  
I forgot QtWidgets magic because switched to Qt QML, but AFAIK QSplitter class be used for this kind of stuff.  
That allow users to use screen space more effective, e.g. if he/she do not need branch list.

Right now right panel can be hide using "Minimalist view" button, probably it can be replaced with splitter.
Maybe other users think this is sufficient

**Comment by francescmm** [comment]
@eraxillan I'm doing several UI/UX tests with the QSplitter and although I see the point of resizing the widgets, I would add a minimum to how much you can "minimize" the size. After that threshold, the resized widget will hide. That's how the splitter works.

What I want is to add a "button" that substitutes the dots/handler of the splitter on every side. I don't like how it looks and definitely prefer the minimalistic approach of the BranchesWidget when one wants to save space.
