### ISSUE TITLE
[MacOS] Font sizing

### ISSUE THREAD

**Issue by fizzyade** [francescmm/GitQlient#199]
I think I've mentioned this on reddit, but the font is way too small on macOS, my eyesight isn't great at the best of times but I find it almost impossible to read on my MBP.

**Comment by francescmm** [comment]
I'll try my best to get an Apple device or find someone to pair on it! This should be in 1.3.1 as well. Didn't forget ;)

**Comment by francescmm** [comment]
Hi @fizzyade I was wondering if the general font-size of GitQlient is a problem or it's some specific widget or part of the app.

**Comment by alluLinger** [comment]
@francescmm  
Buttons look ok, but TextEdit and ListView too small

![截屏2021-04-02 上午9.39.45.png](https://i.loli.net/2021/04/02/tyS1TBMfjEk6u9C.png)
![截屏2021-04-02 上午9.42.44.png](https://i.loli.net/2021/04/02/f8JBY5Skbdiqp2w.png)

**Comment by francescmm** [comment]
@fizzyade @alluLinger I got a Mac so I can move with the tasks now. The first I've done is to fix the DMG, so in the next version you will get one :D

Let's see if I can focus on the font size. I also find it a bit small in the Tree/List/Table widgets. I'm thinking that it might be the default font used on the Mac + the retina display.

**Comment by fizzyade** [comment]
You're going to find that you will need to do a lot of adjusting of stuff for macOS, pixel here, pixel there and so on.  

I'm a mac user, so my primary platform for development is macOS, but I spend a lot of time with tools for enlarging parts of the screen when I'm developing.  For the most part I've found that Windows & Linux generally work in a similar way, less tweaking between those platforms.

I have a machelper library as well in github which provides a bunch of stuff that might be useful for making things "more mac like", because of the way Qt works & renders, often stuff can stick out like a sore thumb on macOS where Qt have drawn a control to "look like" a native mac one, I added code for the menu bar icons + NSPopover because the one provided in Qt was poor and didn't look right.

**Comment by francescmm** [comment]
Well, nobody said it was going to be easier, but we'll see :smile: 

The only think is that I might not be as fast as I'm when shipping features since my main environment is Linux. But I hope I'll be able to put some time on it.

**Comment by francescmm** [comment]
@fizzyade @alluLinger in #220 I've made the diffs and the text edits able to change the font point size from options.

I know there are other places where it could be improved, I'll check soon how it looks in a MBP.

**Comment by francescmm** [comment]
I'll close since it's too old and nobody has asked for any other changes
