### ISSUE TITLE
[BUG] build error

### ISSUE THREAD

**Issue by AlbanMinassian** [francescmm/GitQlient#204]
- OS: ubuntu 20.04

```
uname -a
Linux hppro 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

sudo apt-get install build-essential
sudo apt-get install qt5-default
qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

git clone https://github.com/francescmm/GitQlient.git
cd GitQlient
qmake -project
qmake
make

Makefile:1823: avertissement : surchargement de la recette pour la cible « main.o »
Makefile:1819: avertissement : ancienne recette ignorée pour la cible « main.o »
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -IQLogger -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o BranchDlg.o src/aux_widgets/BranchDlg.cpp
In file included from src/aux_widgets/BranchDlg.cpp:2:
./ui_BranchDlg.h:19:10: fatal error: CheckBox.h: Aucun fichier ou dossier de ce type
   19 | #include "CheckBox.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1827 : BranchDlg.o] Erreur 1


```
Where find build instruction ?
Thank :-)

**Comment by AlbanMinassian** [comment]
Found <https://francescmm.github.io/GitQlient/#appendix-b-build> !

```
 qmake GitQlient.pro
Info: creating stash file /home/dev/Dev/GitQlient/.qmake.stash
Project ERROR: Unknown module(s) in QT: svg webenginewidgets webchannel
```

**Comment by francescmm** [comment]
I don't know what exactly Ubuntu has _by default_. I usually (and encourage) to get Qt FW through the maintenance tool.

Do you know if installing `qtwebengine5-dev` solves the problem?

**Comment by JJRcop** [comment]
@francescmm This exposes an interesting problem: The project completely lacks build instructions! I would suggest adding them with some simple dependencies, and build instructions. This prevents issues like this from happening in the future, and lets people know how to build from source, if they want to do that.

**Comment by francescmm** [comment]
@JJRcop I'm sorry but I cannot agree that the project **completely** lacks build instructions. You can actually find them in here. I agree, though, that they could be more clearly referenced in the front page and so I will do.

Regarding the dependencies, I'll write down what needs in terms of Qt Framework but through the official Qt installer. The main reason is that I cannot keep track of the package naming that every distro decides to use.

**Comment by JJRcop** [comment]
> The main reason is that I cannot keep track of the package naming that every distro decides to use.

That's fine, you don't need to. Your solution is perfectly fine, people can find the deps themselves.

**Comment by francescmm** [comment]
Documentation updated! I'll merge it into master quite soon. I plan to release 1.3.1 during this week.
