### ISSUE TITLE
Relax hard constraint on commit summary length

### ISSUE THREAD

**Issue by alex-ball** [francescmm/GitQlient#206]
GitQlient enforces a maximum line length of 50 characters for the commit summary line. While keeping to around 50 characters is accepted best practice, it may not suit every repository to have this as a strict maximum. It would therefore be handy if this limit could be relaxed in some way. Here are a few suggestions:

1. Make the (hard) maximum summary length configurable, either as a global or per-repository setting.

2. Make the displayed "number of characters left" relate to a target length, rather than a hard limit, so the user is able to type beyond it and the number would either remain zero or go negative.

3. Combine the two so that you have, say, a target length of 50 and a configurable hard maximum that defaults to 72.

**Comment by francescmm** [comment]
Hi @alex-ball,

Thanks for the report. I've introduced this feature in GitQlient 1.3.1. The new maximum value is 99:

![image](https://user-images.githubusercontent.com/4884514/114275836-5e81d800-9a24-11eb-9e9b-2d5b7828c0a8.png)

**Comment by alex-ball** [comment]
Good to hear. But is this platform dependent? Because this is what I see in the AppImage:

![GitQlient-1 3 2-settings](https://user-images.githubusercontent.com/1890395/114359421-ddcdf380-9b6b-11eb-8eb0-63b4fed533f7.png)

**Comment by francescmm** [comment]
It is platform independant. You can find the new configuration widget under the Config tab when you open a repo. So far it's a repo-based configuration, although I could extend it to the whole GitQlient.
