### ISSUE TITLE
CommitInfoWidget doesn't resize with the sidebar

### ISSUE THREAD

**Issue by dasyad00** [francescmm/GitQlient#207]
**What current behavior doesn't fully fit your needs? Why?**
Currently, the CommitInfoWidget does not resize with the sidebar like CommitChangesWidget.

**What you'd like to see? Propose a solution**
Make CommitInfoWidget dynamically sized similar to CommitChangesWidget.

**Describe alternatives you've considered**
If possible, have all widgets on toolbars be resizable. I'm not too fluent in C++ but it would be nice if there is some abstract toolbar class (if there already is, ignore this comment).

**Additional context**
I've just discovered this git GUI client today and I'm very much interested in using this as my main GUI client. I hope this change will further improve the client!

**Comment by francescmm** [comment]
@dasyad00 the previous commit should fix the issue. Thanks for reporting!
