### ISSUE TITLE
[BUG] Preferences tab is unreadable due to white both background and foreground

### ISSUE THREAD

**Issue by band-a-prend** [francescmm/GitQlient#208]
**Describe the bug**
Preferences tab is unreadable due to white both background and foreground:  

I use system Breeze (light) theme with default dark theme in GitQlient.

P.S. switching to "bright" theme in GitQlient isn't work for me.
Affected versions: `1.3.0`, `1.3.1`, build from `develop` branch.
On the `1.2.0` theme switching work.

**To Reproduce**
1. lauch GitQlient-1.3.1
2. Choose git repo to open.
3. On the git tree page open "Preference" tab

**Expected behavior**
The "Preference" tab with `dark` background and `light` foreground is presented.

**Screenshots**
![gitqlient_preference_tab](https://user-images.githubusercontent.com/18756734/114268354-54061500-9a09-11eb-89c1-2fde460b0f3f.png)  

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Release version or SHA: >=1.3.0
 - If manually compiled, compiler version: GCC-10.2.0

**Additional context**
- Qt-5.15.2 is used in system.

**Comment by francescmm** [comment]
Hi @band-a-prend!

Thanks for reporting. I realized that _at least_ 1.3.1 version contains an error in how the settings are populated so it's actually not working!

Fixed now in develop in case you want to try it :)

**Comment by band-a-prend** [comment]
Thank you!
I built from commit de2d2223 of develop branch and now dark/bright themes displaying is right.
The switch between themes works too.
