### ISSUE TITLE
lag in windows10  

### ISSUE THREAD

**Issue by trockxi** [francescmm/GitQlient#209]
I often freeze during use, hoping to improve the experience.

**Comment by francescmm** [comment]
Hi @trockxi , from my experience it's more the lag that _git.exe_ has when executed on Windows that GitQlient. I have some plans to improve the performance on GitQlient so it doesn't get affected by the lag in general, making the execution of git commands kind of asynchronous.

Let's see how that goes in 1.4.0.

**Comment by francescmm** [comment]
If you are able to compile GitQlient locally I would suggest you try the branch pre_1.3.3. There are some nice improvements that I think they'll help. I've tested them and it seems it improves a bit the lag.

However, the main problem is the amount of CPU that Git Bash seems to use in Win10.
