### ISSUE TITLE
[BUG] Required libraries are missing

### ISSUE THREAD

**Issue by FoxTrot75** [francescmm/GitQlient#212]
Install GitQlient 1.3.2 on clean Windows 10

![1](https://user-images.githubusercontent.com/59334095/117537829-1c8c8780-b00c-11eb-8a65-5fcd887bbd17.png)

**Comment by francescmm** [comment]
This library is part of the Visual C++ Redistributable for Visual Studio 2015. This should be already installed after some Windows 10 updates. But just in case, here is the download from microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=48145
