### ISSUE TITLE
Improve documentation for oboarding developers (starting with a graphic linking sourcecode to different parts of the UI)

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#215]
**What current behavior doesn't fully fit your needs? Why?**

If a developer wanted to get involved with this project it would be hard from them to understand what code is associated with aspects of the UI.

**What you'd like to see? Propose a solution**

It would be really useful to have a screenshot of the UI with different labels noting the source code files `.[cpp|h]` associated with it. Obviously this is something that is subject to change because which is the nature of code and progress, IOW upkeep of this documentation  

**Describe alternatives you've considered**

TBD

**Additional context**

N/A

**Comment by francescmm** [comment]
I think this is a great idea! :smile:

**Comment by francescmm** [comment]
Hi @luzpaz, I hope [this documentation](https://francescmm.github.io/gitqlient/) helps you or other developers with the onboarding on GitQlient. I've add it to the branch and it will be merge into master in the following version.

**Comment by luzpaz** [comment]
Woah! That's incredible! Thank you!!
