### ISSUE TITLE
[Feature] Display shorthand version of a hash + add hover tooltip and functionality to "Click to save"

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#216]
**Describe the solution you'd like**

Currently the whole git hash of a commit is shown in the UI. This takes up a unnecessary space and is visually cluttery. Instead show the short version of the hash and add the functionality that if user hovers over it (most likely to copy it) that they are presented with a tooltip that pops up saying something like `Click to save`. Then add this functionality that autsaves hash to buffer upon click 
 
**Describe alternatives you've considered**
N/A

**Additional context**

![gitqlient-hash-feature-request](https://user-images.githubusercontent.com/4140247/126065026-3eeedf45-1e01-4423-9012-f4df2d708a47.png)  
_Above: top portion shows current UI, bottom shows proposed change_

**Comment by francescmm** [comment]
Hi! Thanks for reporting it!

From UX pov, do you think it would be better to underline the hash to show that it's something reactive?

**Comment by luzpaz** [comment]
IMHO, you can do something like:
commit: **BOLDED_HASH**  
and you can for sure bet that someone will hover over it to try and copy. So I think the contrast between the word 'commit:' and the bolded hash will be intuitive enough.

**Comment by francescmm** [comment]
I'll have it underline for now since the implementation was already there. I'll see if it's worth it the logic for bold in the future.
