### ISSUE TITLE
[Improvement] Consider making scroll bars narrower and less promiment (color-wise)

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#217]
**What current behavior doesn't fully fit your needs? Why?**

Currently the scroll bar width / height (depending on the orientation of the text) take up a lot of unnecessary space in the UI.

**What you'd like to see? Propose a solution**

Narrower scroll bars with more transparent background and less prominent colors (make 'black square' (at the intersection of top/bottom and left/right scrollbars) more transparent).  

**Describe alternatives you've considered**

N/A

**Additional context**

Will try to add a screenshot soon

**Comment by francescmm** [comment]
Hi @luzpaz , would be useful as well to indicate the version you're running as well. In the latest version of GitQlient the bars of the scroll have decreased a lot!

If it's in the last version, I will need the screenshot then, just to see what exactly do you mean :smile:

**Comment by luzpaz** [comment]
oh shoot sorry for omitting that! v1.4.0

**Comment by francescmm** [comment]
Could you attach a picture of what you have in mind?

**Comment by luzpaz** [comment]
https://user-images.githubusercontent.com/4140247/130356492-a15ff80e-58ae-40b7-9039-59fd1e3865bf.mp4

**Comment by francescmm** [comment]
I guess that would be the substitute for the whole scroll bar, right? If so, I like it :D

**Comment by luzpaz** [comment]
:tada:
