### ISSUE TITLE
[BUG] Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by mhcwebdesign** [francescmm/GitQlient#218]
**Describe the bug**

**To Reproduce**
1. Download gitqlient_1.4.0_amd64.deb
2. Install via GDebi Package Installer
3. From command prompt run this:
/usr/local/bin/gitqlient
4. It then shows this error:
qt5ct: using qt5ct plugin
/usr/local/bin/gitqlient: symbol lookup error: /usr/local/bin/gitqlient: undefined symbol: _ZdlPvm, version Qt_5

**Expected behavior**
The normal opening screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 XFCE

**Comment by francescmm** [comment]
Hi @mhcwebdesign and thanks for reporting it.

I'm not an expert on packaging so I'd might take extra time for me to figure out what's going on. My first guess is that it's a problem of the version which GitQlient is compiled and packaged and the one existing in the system.

What version of Qt do you have installed?

**Comment by mhcwebdesign** [comment]
They are all based on libqt5core5a, see attached listings.
![Screenshot_2021-08-02_10-12-02](https://user-images.githubusercontent.com/2989557/127836247-dac965d3-5c8c-4b6a-95de-99210e05831b.png)
![Screenshot_2021-08-02_10-10-30](https://user-images.githubusercontent.com/2989557/127836253-46320bc6-6f7d-4dc1-af67-27befc9b01f2.png)
![Screenshot_2021-08-02_10-09-55](https://user-images.githubusercontent.com/2989557/127836256-b0bc6f50-1d83-4e49-a520-8af7bcba462c.png)

**Comment by francescmm** [comment]
Hi @mhcwebdesign, I think I might have found the issue. Apparently I was compiling in Ubuntu 18.04 and that's just old. I've released a new version that should work with 20.XX.

Could you please try [1.4.1](https://github.com/francescmm/GitQlient/releases/tag/v1.4.1) release I comment in this thread?

**Comment by mhcwebdesign** [comment]
I am still getting this:

```
~$ /usr/local/bin/gitqlient
qt5ct: using qt5ct plugin
/usr/local/bin/gitqlient: symbol lookup error: /usr/local/bin/gitqlient: undefined symbol: _ZdlPvm, version Qt_5

```

**Comment by francescmm** [comment]
Okay, I'll try to make some changes and compilations to see what could be the problem. I'll close the release for now.

**Comment by francescmm** [comment]
Hi @mhcwebdesign, I've created a package that it seems to work, if you can test it, once validated I'll create a new version. You can [download the DEB from here](https://www.dropbox.com/s/m2xsezlczhn4krh/gitqlient_1.4.0_amd64.deb?dl=0).

**Comment by mhcwebdesign** [comment]
I just tested your updated gitqlient 1.4.0, and it now works!
Thanks.

**Comment by francescmm** [comment]
Cool, I'll update the license and ship a new version with that :)
