### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sergeiiurin** [francescmm/GitQlient#219]
**Describe the bug**
freshly installed latest Ubuntu 20.04.3, app starting but after that crashes if I'm trying to do anything in the app (open repo, clone etc)

**To Reproduce**
1. install gitqlient_1.4.2_amd64.deb
2. open app
3. clone/open repo

**Expected behavior**
normal behavior like gitqlient_1.4.2_amd64.Appimage has

**Screenshots**
![2021-08-29_22-01](https://user-images.githubusercontent.com/85898717/131287683-c288e894-4edb-4176-8b84-c3c39e4a6e0b.png)
![2021-08-29_22-02](https://user-images.githubusercontent.com/85898717/131287707-2ded7079-b2c6-4f3a-a42d-cf97ef072fbb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Release version or SHA: 1.4.2 deb 
 - If manually compiled, compiler version: no 

**Additional context**
love your app, plz keep going, it is possible to live with Appimage, but it would be great to have .deb option

**Comment by francescmm** [comment]
I believe this is due to the crash I solved here: f865807baec00691fdf06ec7dc39aec6f77c571f

I'll probably ship a hotfix, weird that this hit the DEB and not both that and the AppImage.

**Comment by francescmm** [comment]
@sergeiiurin I've pushed a change(d9b6584e9782236e89ea822f918b831ee70735f9) in the workflow (missing version and that's why it crashed there) and a check in the code. That should solve any problems.

Wait 15 mins and you'll have it in the releases :)
