### ISSUE TITLE
Feature: Show avatar of remote repo instead of generic folder icon

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#227]
**Describe the solution you'd like**
This is similar to #226 but in regards to the Remote repository list in the UI. The current UI just shows a default folder dialog. Instead, we could grab the avatar associated with the remote repository and display for UI richness and better differentiation (for example, in projects that have many remotes)  

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/4140247/146424642-695f7c79-80ea-45dd-85ae-5820b9234e56.png)

**Comment by francescmm** [comment]
Hi @luzpaz, this has more or less the same complexity that I describe [here](https://github.com/francescmm/GitQlient/issues/226#issuecomment-1001211112).

So, I'll hold it for now but thanks a lot for the suggestion!
