### ISSUE TITLE
Feature: make sidebar section size modifiable

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#228]
**What current behavior doesn't fully fit your needs? Why?**

Sidebar sections are static. Screen real estate is an issue on laptops. On a small screen these sections are truncated and require them mouse to scroll through. Also certain sections are more important than others. 

**What you'd like to see? Propose a solution**
A way to click drag the border of a section up or down (and for gitqlient to remember the UI config of each specific repo that is alterered).

**Describe alternatives you've considered**
Invest in a larger screen. 

**Additional context**

![image](https://user-images.githubusercontent.com/4140247/146432141-e142f345-47e4-4ff3-8c27-a3eac637477c.png)

**Comment by francescmm** [comment]
I really love the "Invest in a larger screen" alternative :rofl: 

As a note, the difference between "Local", "Remote", and "Tags" compared to the other sections is that these are based on QTreeWidgets, so it's not possible to add a "minimize" icon in the header. In addition, hiding the viewport is also not helping reducing the size and the truncation.

I'll investigate further about the re-organization and if it would be possible to completely hide every tree individually through the configuration of GitQlient.

**Comment by francescmm** [comment]
The sections are now foldable but I won't implement the re-roder of widgets since make them foldable solves the issue with the size.
