### ISSUE TITLE
Scrollbar breaches the heading area in the sidebar

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#230]
**What current behavior doesn't fully fit your needs? Why?**
![image](https://user-images.githubusercontent.com/4140247/146622373-f69e36bf-f8ba-45be-801c-38046eb2d5d4.png)

It seems that the scroll bar should stay outside of the heading area.

**What you'd like to see? Propose a solution**

Separated and only scrolls the section associated with it.

**Describe alternatives you've considered**
keep as it

**Comment by francescmm** [comment]
Hi @luzpaz, I would say that this is more of a bug that an improvement. I'll check it right away!

**Comment by francescmm** [comment]
Hi @luzpaz, I would say that this is more of a bug that an improvement. I'll check it right away!

**Comment by francescmm** [comment]
After checking, I can say that this is the desired behaviour, after refactoring the scroll bar I've reduced the space on the top so there is more scroll space.

As part of this issue, though, I've added a border so it doesn't seem like a mistake and one knows where the header ends.

This will probably change if the widgets can be reallocated in the future.
