### ISSUE TITLE
Feature: Add a minimap to upper right corner in edit mode

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#231]
**Describe the solution you'd like**
minimaps are common and quite useful to orient oneself and scroll through a document 

**Describe alternatives you've considered**
Not having one

**Additional context**
Example of a [minimap](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap)

**Comment by francescmm** [comment]
Hi, the editor integrated in GitQlient is meant to be more of a helper and not a fully capable editor. The complexity of this minimap is too high to allocate time for it.

**Comment by francescmm** [comment]
I've marked it as "help needed" in case someone else wants to contribute, otherwise I'll close it in ~6 months :smiley:

**Comment by luzpaz** [comment]
@francescmm what is the editor used in gitqlient?

**Comment by francescmm** [comment]
It's not such an editor _per se_. It's actually a text editor with some C++ color highlight and a search feature. It was never meant to be an full capable editor but rather a helper when conflicts happen.

**Comment by isgursoy** [comment]
Would https://github.com/Longhanks/qtcreator-plugin-minimap be helpful?

**Comment by francescmm** [comment]
I took a look some time ago but the plugin is dead since 2 years ago. The problem for integrating it in GitQlient is that the plugin relies in QtCreator specific code, is it's not that adaptable, sorry :disappointed:

**Comment by isgursoy** [comment]
I am recompiling for new qtc releases and actively using it, quite stable. Maybe GitQlient qtc plugin can use it? Better than nothing :)

**Comment by luzpaz** [comment]
@isgursoy would you be open to make a PR that I could pull and test ?

**Comment by isgursoy** [comment]
I would take hunk view as higher priority when I have a free slot for it :)

**Comment by francescmm** [comment]
> I am recompiling for new qtc releases and actively using it, quite stable. Maybe GitQlient qtc plugin can use it? Better than nothing :)

The problem here would be the same, the plugin relies a lot on QtCreator code whereas GitQlientPlugin is basically a layer on top of GitQlient to make it compatible, but doesn't have any dependency on QtCreator.

I'd like to make it possible in the future to use plugins in GitQlient, but this is too far away.

I think that it's better to actually fix the Hunk View and then try to adapt the plugin code to generalize it in QtCreator. It shouldn't be that difficult, rather time consuming.

**Comment by francescmm** [comment]
@isgursoy may be this comment isn't related 100% with this ticket, but it does with your last comment: the hunk view is finally available. And it will be part of the 1.5.0 release. It also includes the stage by line 😄

**Comment by isgursoy** [comment]
GitQlient is getting really serious alternative. Probably I wont renew my GitKraken subscription next time.

**Comment by francescmm** [comment]
That was my intention! The main reason I started this project is becuase GitKraken change their policy for private repos from one release to another.

I wasn't going to pay for something I can do by myself :)

**Comment by francescmm** [comment]
I'll close it since there doesn't seem to be any development related with this I the prio is too low.

**Comment by francescmm** [comment]
I'll close it since there doesn't seem to be any development related with this I the prio is too low.
