### ISSUE TITLE
[BUG] [MacOS] "gitqlient" is damaged and can't be opened

### ISSUE THREAD

**Issue by harens** [francescmm/GitQlient#234]
**Describe the bug**

When I try to run the macOS app from the [1.4.3 release dmg](https://github.com/francescmm/GitQlient/releases/download/v1.4.3/GitQlient-1.4.3.dmg), it appears damaged.

I think it has to do with how the app is signed, since https://github.com/wiverson/maven-jpackage-template/issues/49#issuecomment-997057118 fixes it for me:

```
sudo xattr -rd com.apple.quarantine gitqlient.app
```

**To Reproduce**
1. Download the [1.4.3 release dmg](https://github.com/francescmm/GitQlient/releases/download/v1.4.3/GitQlient-1.4.3.dmg).
2. Double click the app.

**Expected behavior**
It's expected to run accordingly.

**Screenshots**

![image](https://user-images.githubusercontent.com/12570877/148656009-ab6cb1bf-0346-4643-987b-10405267245e.png)

On a side note, the icon doesn't show and I'm not sure why. This issue might be specific to me, but I thought I'd mention it.

![image](https://user-images.githubusercontent.com/12570877/148656020-82bc7d88-2189-47f8-ad4f-0b83de411003.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.1 20C69 x86_64
 - Release version or SHA: 1.4.3
 - If manually compiled, compiler version: N/A

**Additional context**

I really love this project, so I wanted to help how I could. I don't think I can assist in fixing this, but I have an alternative solution. PR incoming. 🚀 

Thank you for your help 😃

**Comment by francescmm** [comment]
Hi @harens and thanks for the contribution! I'll merge the PR and hopefully I'll make some time next week to check the issue on MacOS.

Last time I compiled it worked although the signing was an issue. The problem is that it seems I need to pay a "yearly" fee to Apple to sign a package what is not going to happen in an open source and free software. I'm quite furious about them in that regard, hehehe. IDK, may be things have changed :D

**Comment by harens** [comment]
> Hi @harens and thanks for the contribution! I'll merge the PR and hopefully I'll make some time next week to check the issue on MacOS.

That's very kind of you. Thank you :)

> Last time I compiled it worked although the signing was an issue. The problem is that it seems I need to pay a "yearly" fee to Apple to sign a package what is not going to happen in an open source and free software. I'm quite furious about them in that regard, hehehe. IDK, may be things have changed :D

If I produced a dmg that installed into `/opt/gitqlient/` that I can be fairly sure gets around the signing issue, would you find that useful? I've done something similar before in https://github.com/lite-xl/lite-xl/issues/626 and I'd be happy to do it here. See that issue for more info.

Thanks again for continuing to keep this really useful project going @francescmm. I am very grateful for the work you've put into this.

**Comment by francescmm** [comment]
Hi @harens, feel free to ship a PR with the changes! It would be nice if I would get it included as part of the GitHub actions. When I installed GitQlient in the MacBook it was using the file generated by those actions :thinking:

**Comment by harens** [comment]
@francescmm I was just thinking that since nobody else has reported this error until now, it might be better to keep the current setup.

If someone does have this issue, they can run `sudo xattr -rd com.apple.quarantine /Applications/gitqlient.app` which should fix it for them. It might be simpler just to document this fix? (which I'm happy to do)

**Comment by francescmm** [comment]
Happy if you can ship a PR. Thanks a lot!
