### ISSUE TITLE
Unsure where the log files are stored

### ISSUE THREAD

**Issue by Pysis868** [francescmm/GitQlient#238]
**What current behavior doesn't fully fit your needs? Why?**
Unsure where the log files are.

**What you'd like to see? Propose a solution**
New help text in program under the disable checkbox.
Documentation and readme updates.

**Describe alternatives you've considered**
Looking for `/var/log/git*.log` files.

**Additional context**
I wanted to see how certain Git commands are executed paired with UI actions.
I now see that messages are written to `$HOME/logs/GitQlient.log`.

**Comment by francescmm** [comment]
Hi @Pysis868, I've added a config value where the logs folder is located and the ability to change it.
