### ISSUE TITLE
[Feature Request] Can we have a hunk view (like GitKraken)?

### ISSUE THREAD

**Issue by isgursoy** [francescmm/GitQlient#239]
Is https://github.com/francescmm/GitQlient/issues/26 feature missing or am I missing it?

**Comment by francescmm** [comment]
Hi @isgursoy! I'm not sure if what you mean is the ability to see all changes in a commit or in a file.

To see all the changes in a commit, just double click the commit in the graph view.

To see all the changes in a file for a specific commit in the graph view, and then double click the file in the left panel. That should open a new "diff" view where you should be able to select split/unified view. Showing the hunk view in the unified one.

If that's not what you were looking for, could you send me an image with an example of what you'd like?

**Comment by isgursoy** [comment]
![discard-line-hunk](https://user-images.githubusercontent.com/2170245/151710607-1d93f30b-b7bb-43b8-b560-8fdaa90ab64c.gif) from [GitKraken](https://support.gitkraken.com/working-with-commits/staging/)

**Comment by francescmm** [comment]
This is really nice... I should definitelly do something like this :p

**Comment by isgursoy** [comment]
Yeah really useful and would not be a very radical feature to add on diff view. I can not think a git GUI without hunk view anymore.

**Comment by isgursoy** [comment]
Also related to https://github.com/francescmm/GitQlient/issues/165 so we can close them both when we have this.

**Comment by francescmm** [comment]
GitQlient has something like that. Not easy to find, I must say :sweat_smile: 

If you double click a modified untracked file and then you choose the "Split file view", you will se the changes and you can "add" the _chunks_ (I'm gonna say typo) to the commit.

Not easy to find, not pretty, but it's what I had time so far. The _hunk/line_ is quite a difficult one to do.

**Comment by isgursoy** [comment]
Hmm yes i never right clicked on split view diffs until you point. Looks like only discard option is missing. Why it is hard to show them stacked instead of side by side (not critical) and not showing unnecessary not changed text?

**Comment by isgursoy** [comment]
I guess we should close this issue as it is already in your agenda under #165.

**Comment by francescmm** [comment]
BTW @isgursoy I've decided to create something similar to what you were asking for. I think that the UI as it is right now is not as intuitive as it should.

It will take some time and hopefully it will include the stage by lines, but that specific part I'll do it in the other issue.

If you'd like to give it a try, I have the branch **file-hunk-view**. I cannot ensure that it will fully work right now (although it should!).
