### ISSUE TITLE
Provide a CSS for bright colors

### ISSUE THREAD

**Issue by francescmm** [francescmm/GitQlient#24]
Right now GitQlient only has dark colors schema. It would be nice to have both dark and bright.

**Comment by laurent-simon** [comment]
Good try, the bright color scheme is better! 

For visual comfort and readability, I think that some contrast adjustments are required:

* Files lists on the left are a bit hard to read: there is not enough contrast between the foreground color (light orange and light green) and the background (white). The text foreground color should be a bit darker to be more readable.
* The lists headers are a bit aggressive: The contrast between the main background (white) and the background of headers (dark grey) is high. I think that a little bit softer grey will be better, but just a little.

**Comment by francescmm** [comment]
Hi @laurent-simon, let's work on that then!

**Comment by francescmm** [comment]
I hope you find them more usable! :smiley:

**Comment by francescmm** [comment]
I hope you find it more usable!

**Comment by laurent-simon** [comment]
Yes, it is. It's good for me.
