### ISSUE TITLE
[BUG] One of staged files are excluded from commit

### ISSUE THREAD

**Issue by isgursoy** [francescmm/GitQlient#240]
Staged files reappear back in the local changes pane. If there is a single file, the commit has no changes then.

**Comment by francescmm** [comment]
Hi @isgursoy , thanks for the report. I've seen it happening from time to time but never been able to catch in on debug. I need to setup a test battery to see if I manage to reproduce it with the debugger. It is not clear what is wrong in all that code.

**Comment by isgursoy** [comment]
It is happening everyime you commit. At the beginning I thought having those files opened in IDE could trigger that bug but no, always happening.

**Comment by francescmm** [comment]
Are you running master or a specific version?

**Comment by isgursoy** [comment]
v1.4.3 standalone, ubuntu 20.04

**Comment by francescmm** [comment]
Just find it @isgursoy ! Net release will hopefully solve it :D
