### ISSUE TITLE
Improvement: offer non-git jargon for `git amend`

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#245]
**What current behavior doesn't fully fit your needs? Why?**
![Screenshot_20220402_125723](https://user-images.githubusercontent.com/4140247/161393312-306cf01c-33fd-4ade-b885-0c1a5a0636e5.png)
New users of git won't necessarily know what this means

**What you'd like to see? Propose a solution**
![Screenshot_20220402_125723-1](https://user-images.githubusercontent.com/4140247/161393350-de57beb6-48a6-4625-bbc6-750b5c94ccfc.png)
Add something like `(edit commit message)`

**Describe alternatives you've considered**
n/a

**Comment by francescmm** [comment]
I think it's a nice idea to guide new Git users into this, but in this case amend is more than just editing the message (although users might use it that way more often).

Hiding the real Git command might be okay some times, but in general I'd prefer if users know what that means. I can add a tooltip in this case saying "Edit last commit" and let the user decide.
