### ISSUE TITLE
[BUG] Messed up GUI Scaling on KDE Plasma (With Global Scaling)

### ISSUE THREAD

**Issue by Leakbang** [francescmm/GitQlient#246]
**Describe the bug**
On KDE Plasma, I have the `Global Scaling` set to 125% value and this results in graphical glitches, making the application very difficult to work with.

**To Reproduce**
1. In KDE Plasma settings -> Display And Monitor -> Display Configuration, set the Global Scale to 125%

**Screenshots**
![image](https://user-images.githubusercontent.com/51197897/162644440-8a129050-73b7-4ae9-8e45-7c37a4462326.png)

**Desktop (please complete the following information):**
 - OS: Archlinux (Plasma 5.24.4)
 - Release version or SHA: d33ea0d

**Additional context**
I'm running on X11

**Comment by francescmm** [comment]
This ticket it's a bit old and the complexity of this is for the number of people watching the issue.

I'll close it as "Won't do" if nothing else.
