### ISSUE TITLE
[BUG] Crash when adding files to newly created repository.

### ISSUE THREAD

**Issue by hilpara** [francescmm/GitQlient#251]
**Describe the bug**
GitQlient crashes on newly created repo after adding a file.

**To Reproduce**
1. Create a new local repository.
2. Add a file to the folder
3. Wait for update event (void GitQlientRepo::updateUiFromWatcher())
4. It will crash
 `void GitCache::insertWipRevision(const QString parentSha, const RevisionFiles &files)
{
...
if (mCommits[0]) <- beause mCommits has 0 items and it tries to access the index 0.
...
}
`

**Expected behavior**
It should not crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Release version or SHA: 1.50 (Appimage) and 4e4b74d
 - If manually compiled, compiler version: 

**Additional context**
Actually, is there a possibility to add the first branch before adding files? At the moment I see the only option is to do this all first on CLI and afterwards use the GitQlient.

**Comment by francescmm** [comment]
I'm on it, @hilpara! Thanks for reporting!
