### ISSUE TITLE
Provide a complete source tarball

### ISSUE THREAD

**Issue by adriaandegroot** [francescmm/GitQlient#252]
For packagers who would build GitQlient from source -- e.g. people building `.deb`s or `.rpm` or, in my case, FreeBSD `.pkg` files -- it is convenient to have a single source tarball that contains "all the things". All the things is a bit subjective: without bundling / vendoring dependencies, that is. For GitQlient the source repo refers to four submodules (from the *francescmm* GH account); those are unlikely to be packaged separately, so vendoring them into a source tarball is not much of an issue.

**What you'd like to see? Propose a solution**

It would be nice to have a tarball attached to releases that contains all the necessary sources (right now, going to the 1.5.0 release and downloading sources (tgz) does not get you a buildable tree).

**Describe alternatives you've considered**

For packaging, I can of course pull in multiple tarballs and assemble them into a buildable tree myself, but it is a barrier-to-entry.

**Comment by adriaandegroot** [comment]
FWIW, `devel/gitqlient` just landed in the FreeBSD ports tree. For the submodules, I just picked the latest SHAs in each repo, which -- I think -- matches how the submodules are configured anyway.

**Comment by adriaandegroot** [comment]
(As an aside: since GitQlient uses `QFileSystemWatcher`, it is mindbogglingly slow on FreeBSD and hardly usable. That's not GitQlient's fault, but Qt5-on-FreeBSD.)

**Comment by francescmm** [comment]
> FWIW, `devel/gitqlient` just landed in the FreeBSD ports tree. For the submodules, I just picked the latest SHAs in each repo, which -- I think -- matches how the submodules are configured anyway.

That should be alright. Thanks a lot for the port! I'll try to collect all the links to the different distros, so when you're done just past me here the link :)

> (As an aside: since GitQlient uses `QFileSystemWatcher`, it is mindbogglingly slow on FreeBSD and hardly usable. That's not GitQlient's fault, but Qt5-on-FreeBSD.)

It's actually quite unstable in Linux as well, it doesn't always detects the file changes and it depends on the OS to do the notification. But for now I don't have anything better :cry:

**Comment by francescmm** [comment]
Hi @adriaandegroot ! I've added the tarball in the 1.5.0 release. It's probably too late already, but I'll add a command to do it also in the release process :)
