### ISSUE TITLE
Improve special-cases wording of repo-configuration

### ISSUE THREAD

**Issue by adriaandegroot** [francescmm/GitQlient#254]
When opening a repo, the repo-configuration dialog shows number-of-commits to fetch and an autofetch interval. Both have special cases (0 for "all history"; 0 for "never"), so it's more user-friendly to display that. Explaining the special meanings can still be done, although it's less visible.

Patch attached, made with Qt5 designer.

[improved-spinboxes.txt](https://github.com/francescmm/GitQlient/files/8995419/improved-spinboxes.txt)

**Comment by adriaandegroot** [comment]
(I would PR this, but -1- it's trivial -2- I don't feel like figuring out which sub-repo to fork-and-PR-from)

**Comment by francescmm** [comment]
I'll apply it this afternoon. It's the GitQlient repo, so the PR should be easy to do, but I agree that for such a tiny change I can copy-past it directly. Thanks for the contribution!
