### ISSUE TITLE
Add ability to stage changes by hunk and by line

### ISSUE THREAD

**Issue by nocnokneo** [francescmm/GitQlient#26]

**Comment by francescmm** [comment]
Yeah, I would love this too :)

**Comment by nocnokneo** [comment]
I think single clicking on a file in the "Untracked files" or "Unstaged files" list should show the changes (especially once line-by-line staging is implemented) and double click should stage all the changes from the file.

**Comment by francescmm** [comment]
After some investigation this requires a change in how the current files are shown in the WIP widget. That means that it won't be included in the version 1.2.0.

**Comment by francescmm** [comment]
Stage by line will be done in future releases.
