### ISSUE TITLE
Adding push to option like vscode

### ISSUE THREAD

**Issue by fmanlou** [francescmm/GitQlient#267]
Adding push to option like vscode

**Comment by francescmm** [comment]
Hi @fmanlou where are you missing this option?

**Comment by fmanlou** [comment]
> Hi @fmanlou where are you missing this option?

I can't push code to the remote branch of my choice

**Comment by fmanlou** [comment]
I found that vscode does something better.

**Comment by francescmm** [comment]
Could you please describe in detail the workflow you want?

Right now in GitQlient you can push with the following options:

1. If the remote branch doesn't exist, GitQlient will tell you and let you pick the name (by default same name, but you can modify).
2. If the remote already exists, you can push to that branch.

You can do this options from the context menu with right click on the graph view, or in the branches widget in the top right part of the screen selecting your current branch.

**Comment by fmanlou** [comment]
Sorry for my bad English

we use gitlab to manage code, I pull the code from team repository. But I can't commit the code to the team repository. I must commit the code to my fork repository first and then request merge.

I found no way to do this. I must setup remote branch using command. Gitqlient can unset upstream，but why can't it set upstream after unset upstream.

**Comment by francescmm** [comment]
Okay, now I think I know what you want. I'll "repeat" just to confirm:

You want to be able to checkout a remote branch from your team repository, and then push the modifications to your fork repository. So, basically push to a custom upstream.

Am I right?

**Comment by fmanlou** [comment]
It's right!

**Comment by francescmm** [comment]
Then I'll add it to GitQlient! It should be fairly easy :smile: 

I think I'll give two options to do it:

- Allow to set the upstream
- Allow to chose the remote when push

**Comment by fmanlou** [comment]
very good👍👍
