### ISSUE TITLE
Provide an AppImage package

### ISSUE THREAD

**Issue by nocnokneo** [francescmm/GitQlient#27]

**Comment by francescmm** [comment]
Hi @nocnokneo, I've been investigating and trying with AppImage and so far it goes well. The only problem is that I couldn't figure out how to add my icons from the resources.

I load them using the resources.qrc file but it seems not to work with AppImage. Do you have any clue?

**Comment by francescmm** [comment]
Fixed by adding the parameter "-extra-plugins=iconengines,imageformats" to linuxdeployqt

**Comment by nocnokneo** [comment]
Sorry, I wasn't able to help out, but I'm glad you solved it!
