### ISSUE TITLE
rebase

### ISSUE THREAD

**Issue by Virus936** [francescmm/GitQlient#274]
I'd like to see the following options:

    git rebase -- right click on a commit or a branch -> "rebase branchA to here" 
    when you create a branch, space are not allowed so replace space by '-'

Thank you for supporting this GUI.

**Comment by francescmm** [comment]
Hi @Virus936, I've implemented the changes to replace the whitespace for configurable characters, not only '-'. The replacement was already there but I'm not sure if was included in the last version.

The rebase is a bigger option that needs some work similar to merge, so I'll do that in a different ticket.

**Comment by Virus936** [comment]
Hi, 
I tried to configure it but i don't find where i have to. I just installed the 1.6.1 version.

**Comment by francescmm** [comment]
Hi @Virus936, this will be part of the 1.6.2 version that I'll probably release during the weekend :)
