### ISSUE TITLE
Show full diff of commit

### ISSUE THREAD

**Issue by pprkut** [francescmm/GitQlient#275]
**Describe the solution you'd like**
A diff view like gitk has it, where I can select a commit from the log and then have a view that shows all changes for all files without having to select each file individually. Ideally, there'd be a way to have the commit log and the diff view next to each other.
I use a GUI mostly for exploration, to which a good diff view is essential. 

**Describe alternatives you've considered**
The current way is really non-intuitive and cumbersome (for me). It's not clear to me at all that in order to see the diff for a commit I have to double click a file, and then have to double click a different file if I want to see those changes too. If I have a commit that changes a lot of files, getting an overview of all the changes is really complicated, if not impossible.

**Additional context**
I found that what looks like what I want was removed in https://github.com/francescmm/GitQlient/commit/ac3c6ecc37c939ba14cd21f30918160b96483b83, but the commit doesn't provide an explanation why.

**Comment by francescmm** [comment]
Hi @pprkut, I remove it because the look and feel was not great and I wasn't using it that much and I didn't get any feedback after the removal. I can add a context menu option for it for the next release.
