### ISSUE TITLE
Provide an OpenSUSE package.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [francescmm/GitQlient#276]
Since Fedora `.rpm` packages are usually compatible, I doubt much, if any, work is necessary except the publishing process and adding a new option to the CI.

**Comment by francescmm** [comment]
Hi @rokejulianlockhart! Thanks for the suggestion, however I'm not maintener of the RPM package for Fedora/CentOS. I just store the files so the package can be created (and ocasionally I update them).

I'm hopen for anybody that wants to take that task, though :)

**Comment by francescmm** [comment]
This issue has been alive too long without contributions. I'll reopen if somebody wants to work with it, sorry.
