### ISSUE TITLE
[Questions]How to add translation

### ISSUE THREAD

**Issue by ShuiHuo** [francescmm/GitQlient#281]
I added a translation file via qt Linguist, then how do I use this translation?
```
ls src/resources/translations/
gitqlient_en.qm  gitqlient_en.ts  gitqlient_zh_CN.qm  gitqlient_zh_CN.ts
```

**Comment by francescmm** [comment]
Hi @ShuiHuo,

GitQlient right now is prepared for translation (almost all text can be translatable) but it's not ready for it in the sense that there is no option for language selection.

If you want to provide the translations in a PR this can be the moment to implement that in GitQlient. I assume it won't take too much and it will be a nice addition :)
