### ISSUE TITLE
UI font size

### ISSUE THREAD

**Issue by dhardy** [francescmm/GitQlient#284]
Please make the UI font size configurable (the editor font size was already made configurable in 8ce449fa932eaef18f8f0ee659bea3779b1dfac8).

---

Using a 13" 1080p laptop screen (common), standard 8-10pt fonts are too small to easily read (IMO) without scaling. Scaling at 125% fixes the font size but causes ugly scaling in a few cases and a lot of wasted space, so simply increasing font size is often preferable.

I have increased font size in KDE settings, but GitQlient does not appear to respect this.

Related: #199.

**Comment by francescmm** [comment]
Thanks for reporting @dhardy, I'll see what I can do with that!

**Comment by francescmm** [comment]
Hi @dhardy, better later than never but I've pushed a change since the point size was still hardcoded in a couple of places.

Now it should be fine.
