### ISSUE TITLE
[BUG] Cannot open git repo with spaces in the name

### ISSUE THREAD

**Issue by relaxlex** [francescmm/GitQlient#286]
**Open a git repo which has a space in it's name**

**Steps to reproduce the behavior**
1. Create a new git repo with a space in it's name by example: "test repo"
2. change to this directory: `cd "test repo"`
3. Start gitqlient in this directory: `gitqclient .`

**Expected behavior**
Open gitqlient using the git repo

**Error message**
_The Selected path is not a Git repository. Please make sure you opened the correct directory._

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Release version or SHA: 1.6.2
 - Installed from AUR

**Additional context**
Quick fix, just rename the repo to something that does not contain any spaces.

**Comment by grizmio** [comment]
Changing from
```const auto cmd = QString("git -C %1 rev-parse --show-toplevel").arg(path);```
to
```const auto cmd = QString("git -C \"%1\" rev-parse --show-toplevel").arg(path);```
could be a fix or is it too bad? 
I use GitQlient every day and I really hope this minimal proposal will be useful.

**Comment by francescmm** [comment]
I think I have some time today to try to fix some of the issues in the rep. I'll check soon!

**Comment by francescmm** [comment]
I've checked and your solution works for this case. However, I'm not sure of the implications of whitespaces in the repository name in other parts of GitQlient. I guess we'll figure out step by step :)
