### ISSUE TITLE
[Improvement] Branch head labels not readable.

### ISSUE THREAD

**Issue by kralan** [francescmm/GitQlient#288]
**Describe the bug**
With release 1.6.3, branch head labels contain no text but three dots. They worked well with release 1.6.2.

**To Reproduce**
In history view, observe that other than with version 1.6.2, all branch head labels contain no readable text but only three dots. Additional observation: All the labels seem to have the same width now-

**Expected behavior**
Have heads of branches labeled with readable labels.

**Screenshots**
Screenshot attached.
![Screenshot_20241017_172719](https://github.com/user-attachments/assets/b8ffc87a-b675-42f7-a733-bddbaf089583)

**Comment by francescmm** [comment]
Hi @kralan, can you check that expanding the History column fixes the issue? The three dots appear when there is no space for the whole branch name together with the commit message.

**Comment by kralan** [comment]
@francescmm, yes I can make the branch names visible by expanding the History column - thank you. Font sizes may have changed with release 1.6.3 and triggered the issue for me.

Let's not call this a bug then but turn it into an enhancement request:
* If just one single line exceeds the width of the History column, **all** branch names in all lines turn into dots. It would suffice to truncate the names in the affected lines only.
* I would rather have the commit messages truncated than the branch names turned into dots.

**Comment by francescmm** [comment]
Hi @kralan, the font size changed to fix a bug un MacOS but shouldn't have affected the other plataforms, so that I'll check for sure.

I'll also implement your suggestions and, at the very least have the second one activated via settings.

Thanks for the feedback!

**Comment by francescmm** [comment]
@kralan I've pushed the changes and I'll try to create a latest build in master, although marked as development release so it's easier for people to get the latest changes

**Comment by kralan** [comment]
@francescmm the latest development release works for me. Thank you for your fast response and this valuable tool.
