### ISSUE TITLE
Create snap app and publish to snap store

### ISSUE THREAD

**Issue by gocarlos** [francescmm/GitQlient#44]
examples here: https://github.com/ubuntu/snapcraft-desktop-helpers

**Comment by francescmm** [comment]
Hi @gocarlos, I've been reading about Snap and I'm not convinced about it yet. So far what I understood is that id needs to hold all the dependencies inside the package. So at the end someone that has several packages with the same dependencies will have them several times.

That and the fact that it's in a virtual container and could lead to some access problems is what doesn't convince me for now.

I would prefer if the package is a .deb so you can trace it with apt. I'd like a .rpm at the same time, actually.
