### ISSUE TITLE
Can this run on Win 10?

### ISSUE THREAD

**Issue by Frick-David** [francescmm/GitQlient#46]
Hey there, huge fan of this repo. My prayers for a good linux git client have been answered! (plus qt to boot ;) )
One of my co-workers is currently using Win10. Is it possible to build this on Windows 10?

Thanks!

**Comment by francescmm** [comment]
Yes! It's actually quite easy to build for Windows 10. With Qt Creator you just need to compile it like any other Qt app. I added support for both MSVC 2017 and GCC compilers.

If you like you can download the installer from here:

https://github.com/francescmm/GitQlient/releases/tag/v1.0.0

**Comment by Frick-David** [comment]
Okay, thats great! I will try and install it this evening. Can I check back in if I have any issues?

**Comment by francescmm** [comment]
> Can I check back in if I have any issues?

Sure! For any issue you have just open a ticket as you did it for this one! I'll try to be as fast as possible in the response :)
