### ISSUE TITLE
Ability to select mulitple files from a commit to queue for diff

### ISSUE THREAD

**Issue by djotaku** [francescmm/GitQlient#48]
I noticed you have this awesome feature where each file selected to diff will appear on the diff page so that one can select back and forth between them. But in order to put a bunch of files on there, you need to go back and forth between repoview and diff view. Should be able to use shift or control to select multiple files to diff.

If need more clarity on the issue, see https://youtu.be/4hLlQzepAlg?t=413 (6 min 53 seconds, if that link does not deliver you to the right place)

**Comment by francescmm** [comment]
Hi!

I just saw you video, and thanks for it! I think I already comment it there but I'll try to sum up here. Basically you can double click every thing. If a branch it should checkout the branch, for instance.

In the particular case of a commit, you could double click the commit in the repo graph and that will open the diff view for that commit. Inside the view, then you will be able to open every file in the commit:

![image](https://user-images.githubusercontent.com/4884514/75817803-152e7600-5d98-11ea-86db-641b6187f2a9.png)
 As you can see in the image, there is button for the **commit** diff, and another button for the **file** diff. Different icon too :smile: 

You also can double click in the list at the bottom to open a file of the commit.

I focus so much in adding functionality that I honestly forgot to add a "manual". I'm going to improve the documentation for the next minor version for sure.

Let me know if this behaviour solves your request! :smiley:

**Comment by djotaku** [comment]
Yup, feel free to close
