### ISSUE TITLE
Add more info in the readme about how to compile

### ISSUE THREAD

**Issue by Mte90** [francescmm/GitQlient#5]
To compile is required to download also the git submodules but this is not clear until someone try to compile it.

**Comment by francescmm** [comment]
Thanks for the feedback! I actually have a task to add the License and the Contributions Guidelines. I will definitely add more info in the ReadMe :)

**Comment by francescmm** [comment]
I added more information in the README, please tell me if you're missing anything!

**Comment by Mte90** [comment]
It is better now but it will be better with the git commands to download everything (including submodules) and commands to compile it :-)

**Comment by francescmm** [comment]
Here it is! :)
