### ISSUE TITLE
Support for folder as parameter

### ISSUE THREAD

**Issue by Mte90** [francescmm/GitQlient#7]
I created a desktop file but seems that qgitclient doesn't accept as first parameter the folder to open with this tool.

```
[Desktop Entry]
Type=Service
Encoding=UTF-8
Actions=OpenWithQGitClient
ServiceTypes=KonqPopupMenu/Plugin,inode/directory
ExcludeServiceTypes=kdedevice/*

[Desktop Action OpenWithQGitClient]
Name=Open with QGitCLient
Exec=/path/GitQlient/GitQlient %d
```

**Comment by francescmm** [comment]
Internally it's supported but I wasn't parsing the arguments. It's an easy fix I can do this afternoon :)

**Comment by francescmm** [comment]
Feature implemented! You can add -repos and after that the list of repositories you want to open.

However I'd be good if you can fix your Desktop Entry. %d is a deprecated option. The Desktop Entry I've used is the following:

`[Desktop Entry]
Type=Service
Encoding=UTF-8
Actions=OpenWithQGitClient
ServiceTypes=KonqPopupMenu/Plugin,inode/directory
X-ExcludeServiceTypes=kdedevice/*
X-KDE-Priority=TopLevel

[Desktop Action OpenWithQGitClient]
Name=Open with QGitClient
Exec=/path/to/GitQlient -repos %F`

In #8 there is the option if you want to avoid logs ('noLog').
