### ISSUE TITLE
Logs folder created automatically

### ISSUE THREAD

**Issue by Mte90** [francescmm/GitQlient#8]
It is possible to disable it?
This is creating that folder where I don't need that.
Maybe is possible to configure in `/tmp`?

**Comment by francescmm** [comment]
Right now is not possible to configure it. What I recommend you just to disable it by commenting out the following line in the main.cpp file:

```manager->addDestination("GitQlient.log", { "UI", "Git" }, LogLevel::Debug);```

Take into account that the app is not stable, it's currently under development and it could crash :)

**Comment by Mte90** [comment]
in case add a parameter so I don't need to hack that?

**Comment by francescmm** [comment]
I've added the option 'noLog' that you can add in the command line if you don't want any logs :)
