### ISSUE TITLE
List of remotes shows only one remote

### ISSUE THREAD

**Issue by mslusarz** [francescmm/GitQlient#80]
Other remotes seem to be inside "origin":

- remote1
  - branch1
  - branch2
  - remote2
     - branch3
     - branch4

**Comment by francescmm** [comment]
Yep. Confirmed! :)

**Comment by francescmm** [comment]
This is partially related with #84. The use and management that GitQlient does of multiple remotes is not yet implemented.

This needs improvement and probably will be part of a new "Remote story" by itself.
