### ISSUE TITLE
Log column is not easily resizable

### ISSUE THREAD

**Issue by mslusarz** [francescmm/GitQlient#81]
By changing the width of the "Graph" column in "View", it's easy to shrink the "Log" column to just a few characters and there's no way to expand it back.

**Comment by mslusarz** [comment]
Huh, the widths of columns are saved somewhere, so restarting the application doesn't help...

**Comment by francescmm** [comment]
Yep, the column configuration is stored in the config of GitQlient. On Linux you can find the file in `$HOME/.config/CescSofware/GitQlient.conf`. You can edit it with a text editor and remove the keys that start with RepositoryView.

I personally couldn't manage to shrink any column to less than 30px. Could you attach a picture?

**Comment by mslusarz** [comment]
![Zrzut ekranu z 2020-04-28 21-33-19](https://user-images.githubusercontent.com/477830/80529677-1646e280-8998-11ea-9fdc-e1b36bf0bc03.png)

**Comment by francescmm** [comment]
Thanks for the picture @mslusarz. I'm going to reset the values for the columns and change their configuration :)

**Comment by francescmm** [comment]
I've modified the way the columns are resized and managed. The main problem here is the deficient management that Qt does in QHeaderView.

The best option would be to extend QHeaderView but it would requires to go as deep as touching the private qheaderview_p.h file. Unfortunately that's completely out of scope for now.

I hope this works better! :smile:
