### ISSUE TITLE
Diff view should show commit metadata

### ISSUE THREAD

**Issue by mslusarz** [francescmm/GitQlient#82]
Author, commit string, etc should be visible in the "Diff" view.

**Comment by francescmm** [comment]
Would you like to see both authors and commit messages for both commits in the diff?

If that's the case I could try to create a tool tip for the SHA.

**Comment by francescmm** [comment]
I've added some info in a tooltip to the commit in the Diff view.

I will reshuffle the Diff view in the following version.
