### ISSUE TITLE
Application crash after name and email validation

### ISSUE THREAD

**Issue by Porkepix** [francescmm/GitQlient#87]
I can't provide much more informations sadly as GitQlient command isn't available in terminal to launch from there, and I had nothing meaningful in journalctl.

This is using the 1.0 release packaged from ArchLinux' AUR: https://aur.archlinux.org/packages/gitqlient/

**Comment by francescmm** [comment]
Is there any logs you could attach? Otherwise I could try to instal an ArchLinux in a VM :)

**Comment by Porkepix** [comment]
If it write some logs somewhere, yes, but as I said I found nothing in `journalctl` and had no command for GitQlient offered to run from terminal.

**Comment by Porkepix** [comment]
Okay, digged a bit. I had no command because I didn't expected the command to have caps.

Didn't got much though:
```
$  /usr/bin/GitQlient
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
double free or corruption (out)
Aborted (core dumped)
```

Coredumpctl have nothing related to GitQlient though, so I have no idea where the core is supposed to be dumped.

**Comment by francescmm** [comment]
It should be a logs folder in `/usr/bin/` after that execution :thinking: 

Probably really stupid question but, have you Git already installed? GitQlient doesn't work through any library but through Git.

That something I should warn when starting GitQlient, actually :thinking:

**Comment by Porkepix** [comment]
Of course I have git, among other things it's a requirement when I use AUR and packages there.
I highly doubt there would be any log folder in `/usr/bin`, considering it would require to be root to write there. Or have sudoers permissions granted.

PS: Okay, at first I missed the logs folder that was created from where I ran the command.
Here's the log file, but I don't think it contains much useful information: https://privatebin.at/?380819f24a5ac6b9#53iznELEi5MVeLdAx7JKp5rFNgtzQ62wQYhPxVSnUZLv

**Comment by francescmm** [comment]
Thanks! I'll check it on ArchLinux as well :)
