### ISSUE TITLE
Improve UI reactivity on Windows. Huge penalties on the UI reaction due to Git queries.

### ISSUE THREAD

**Issue by nicexe** [francescmm/GitQlient#88]
I'm not sure if this issue is related: #65 
This is for version 1.0.0 for Windows.
The biggest issue I have when using GitQlient is [UI reactivity](https://en.wikipedia.org/wiki/Reactive_user_interface). Please have a moment to read this wikipedia article.
I'll be comparing GitQlient with [Fork](https://fork.dev/) for this.
On Fork, clicking on a commit instantly highlights the commit row and about half a second later I get all details about the commit populated in the UI.
On GitQlient, clicking on a commit message takes about 3.5 seconds before anything signifies that something happened or is happening after I clicked.
To be clear. My main issue isn't that it takes 3.5 seconds to get to see the commit details (although this is a separate issue). The main issue is that clicking something should give you an instant feedback if something is about to happen (for example highlighting the clicked commit row before trying to fetch the commit data).

**Comment by francescmm** [comment]
Hi @nicexe,

Thanks for trying it on Windows. Unfortunately, I had to suffer those issues myself on Windows. It seems that there is a huge penalty by using git command directly on windows.

I cannot see how Fork implements the access for git but I'm convinced that not accessing Git Bash directly.

I've done some improvements in the new version I'll publish in 3-4 weeks. It doesn't solve all the problems but you can feel an improvement in the reactivity. The main reason is that GitQlient in the v1.0.0 was doing too many queries to Git bash that weren't unnecessary.

It you could try the new version I'd appreciate it. However, I can honestly tell you that it's not in the same level of performance that Fork right now.

I'll try to dedicate more efforts into Windows for the v1.2.0.

**Comment by francescmm** [comment]
The whole 1.2.0-dev branch is a change of mechanism from executing Git to read first the cache. This improves speed a lot.
