### ISSUE TITLE
Mistake in 1.1.0-beta release asset name

### ISSUE THREAD

**Issue by Symbian9** [francescmm/GitQlient#92]
Release `v1.1.0-beta` has as asset AppImage named as `GitQlient-1.0.0-beta-x86_64.AppImage`, but it should be `GitQlient-1.1.0-beta-x86_64.AppImage`:

- https://github.com/francescmm/GitQlient/releases/tag/v1.1.0-beta
  - https://github.com/francescmm/GitQlient/releases/download/v1.1.0-beta/GitQlient-1.0.0-beta-x86_64.AppImage

Think, this is just typo mistake, but users may be confused.

**Comment by francescmm** [comment]
I've fixed in both the actual beta and in the GitQlient project file.

Thanks!
