### ISSUE TITLE
Initialize a new repository doesn't work

### ISSUE THREAD

**Issue by lmenut** [francescmm/GitQlient#93]
In the "Initialize repository" dialog box, the Accept button doesn't do anything.
In CreateRepoDlg::accept(), line 91
`if (!url.isEmpty() && !path.isEmpty() && !repoName.isEmpty())`
should be fixed for initialization of a new repo, as in this case url is always empty (cf line 22).
A fix could be
`if ((!url.isEmpty() || (mType == CreateRepoDlgType::INIT)) && !path.isEmpty() && !repoName.isEmpty())`

**Comment by francescmm** [comment]
Yep, I realized yesterday when I was testing clone as well. Nice catch!
