### ISSUE TITLE
Create recipe in Homebrew for MacOS

### ISSUE THREAD

**Issue by erikvanoosten** [francescmm/GitQlient#94]
Similarly to #73 and #74 it would be great if GitQlient can be installed on MacOs via Homebrew.

**Comment by MartinDelille** [comment]
Here is [my personnal tap](https://github.com/MartinDelille/homebrew-tap). I'll be happy to host the formula before it is accepted by https://github.com/homebrew/homebrew-cask

Here is [an example formula](https://github.com/MartinDelille/homebrew-tap/blob/master/Casks/teamviewer-quicksupport.rb)

**Comment by francescmm** [comment]
I've created another issue to create a package for OSX. I don't have an OSX machine but I can be triggered via Travis CI (currently compiling, yeah). The problem is that I don't have any experience with OSX to drive this.

@MartinDelille @erikvanoosten If any of you have experience with it I'd be glad if you could help with it :smiley:

**Comment by erikvanoosten** [comment]
Sorry, no experience. I am a JVM user :)

**Comment by MartinDelille** [comment]
I am a git monkey and a macos qt dev so I might help you.

After looking at the code, you would need to create a DMG. I do it here but there still something going wrong uploading the release assets: https://github.com/MartinDelille/chat-qt/blob/master/chat-qt.pro#L46-L59

**Comment by MartinDelille** [comment]
I could drop you a PR if I find time to do so!

**Comment by francescmm** [comment]
Hi @MartinDelille, I've set up the code in the project file. What would you need to do in order to host the formula? How this usually works?

I have no experience with it, TBH.

**Comment by francescmm** [comment]
Just doing a follow up of this task, @MartinDelille . Is there anything you could do about this?

Otherwise I'll close the ticket and if someone and if someone asks for it in the future I can reconsider.
