### ISSUE TITLE
Log view doesn't highlight current branch if switched externally

### ISSUE THREAD

**Issue by MSumulong** [francescmm/GitQlient#98]
I was using GitQlient (v1.1.0) alongside the command-line git to switch branches (ie. git checkout test-branch / git checkout master). After switching the branches in the command-line and then pressing refresh in GitQlient, I expected the log view to highlight/bold the current branch but it doesn't appear to do so. It remains highlighted/bold on the previous branch. However, the branches information view appears to highlight the current branch correctly after refreshing.

**Comment by francescmm** [comment]
I'll check it tomorrow! :+1:
